cfg:
  path_to_features: ./out/features
  path_to_scores: ./out/scores
  path_to_eval_results: ./out/results
  seed: 0
  n_samples_eval: 2500
  train_samples: 2500
  valid_samples: 0
  run_id: 5k
  dataloader_num_workers: 4
