#!/bin/bash
# Same-family ablation for RAR-XXL: synthetic non-members generated by VAR
# (same family as RAR, autoregressive).
#   suspect-set unlabeled U  -> .../imagenet_*_var_last4_cfg1.5/train  (= AE rec)
#   synthetic non-members N  -> .../imagenet_*_var_last4_cfg1.5/val    (= img2img)
# Idempotent: skips runs whose .npz output already exists.
set -e

P=/home/jdubinsk/dataset_inference_dm/duci-pul/.venv/bin/python3
MODEL="${MODEL:-rar_xxl}"
ATTACK="${ATTACK:-llm_mia_cfg}"
GPU="${GPU:-cuda:2}"
RUN_ID="${RUN_ID:-5k}"
OUT_F="$(pwd)/out_ablation_samefamily/features"
OUT_S="$(pwd)/out_ablation_samefamily/scores"
COMMON="++cfg.path_to_features=$OUT_F ++cfg.path_to_scores=$OUT_S ++cfg.run_id=$RUN_ID ++cfg.device=$GPU"

DATASETS=(fp_var_last4 tp_var_last4)

cd /home/jdubinsk/dataset_inference_dm/duci-pul/iars
mkdir -p "$OUT_F" "$OUT_S"

run_or_skip() {
  local outfile="$1"; shift
  if [ -f "$outfile" ]; then
    echo "[skip] already exists: $outfile"
    return
  fi
  echo "[run]  $outfile"
  "$@"
}

for DS in "${DATASETS[@]}"; do
  for SPLIT in train val; do
    # dataset.name in our yamls is 'imagenet' (so the dataset registry resolves)
    # but the override passes ++dataset.name=$DS so the saved filename is $DS.
    run_or_skip "$OUT_F/${MODEL}_${ATTACK}_${RUN_ID}_${DS}_${SPLIT}.npz" \
      $P main.py +model=$MODEL +attack=$ATTACK +dataset=$DS \
        ++dataset.split=$SPLIT $COMMON
  done
done

echo "=== RAR-XXL SAME-FAMILY ABLATION DONE ==="
